# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.srcs/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/riscv_gig_ethernet_pcs_pma_0_0.xci
# IP: The module: 'riscv_gig_ethernet_pcs_pma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.gen/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/riscv_gig_ethernet_pcs_pma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.gen/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/synth/riscv_gig_ethernet_pcs_pma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.gen/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/synth/riscv_gig_ethernet_pcs_pma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.srcs/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/riscv_gig_ethernet_pcs_pma_0_0.xci
# IP: The module: 'riscv_gig_ethernet_pcs_pma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.gen/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/riscv_gig_ethernet_pcs_pma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.gen/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/synth/riscv_gig_ethernet_pcs_pma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ashraf/vivado-risc-v/workspace/rocket64b1/vivado-vc707-riscv/vc707-riscv.gen/sources_1/bd/riscv/ip/riscv_gig_ethernet_pcs_pma_0_0/synth/riscv_gig_ethernet_pcs_pma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_gig_ethernet_pcs_pma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
